"""Framework-neutral task runtime contracts and state machine."""

from .backends import BoundedThreadPoolBackend, CallbackThreadBackend, TaskBackend, ThreadBackend
from .checkpoint import (
    CHECKPOINT_SCHEMA_VERSION,
    CheckpointCorruptError,
    CheckpointError,
    CheckpointExpectation,
    CheckpointFrontier,
    CheckpointFutureSchemaError,
    CheckpointMismatchError,
    CheckpointPort,
    CheckpointRecord,
    CheckpointRevisionError,
    LegacyCheckpointError,
    job_spec_fingerprint,
)
from .checkpoint_fs import FilesystemCheckpointPort
from .controls import (
    CancellationToken,
    CommitPermit,
    CommitResult,
    ControlProjection,
    ShutdownPolicy,
    ShutdownResult,
    StopPolicy,
    StopResult,
    TaskCancelled,
)
from .entrypoints import (
    RuntimeTaskBridge,
    SessionJobGate,
    TaskWaitTimeout,
    TerminalOutcome,
)
from .events import JobEvent, JobEventType, Subscription, TaskEventFilter
from .graph_workload import (
    GraphExecutorPort,
    GraphWorkloadAdapter,
    GraphWorkloadOutcome,
    GraphWorkloadState,
)
from .models import (
    JobCapabilities,
    JobSnapshot,
    JobSpec,
    JobState,
    OwnerRef,
    TaskAccessError,
    TransitionError,
)
from .projection import (
    ControlActionResult,
    RuntimeTaskProjection,
    TaskProjectionPort,
    job_snapshot_to_public_dict,
    job_snapshot_to_view,
    view_age_seconds,
)
from .runtime import TaskRuntime

__all__ = [
    "BoundedThreadPoolBackend",
    "CallbackThreadBackend",
    "CHECKPOINT_SCHEMA_VERSION",
    "CancellationToken",
    "CheckpointCorruptError",
    "CheckpointError",
    "CheckpointExpectation",
    "CheckpointFrontier",
    "CheckpointFutureSchemaError",
    "CheckpointMismatchError",
    "CheckpointPort",
    "CheckpointRecord",
    "CheckpointRevisionError",
    "CommitPermit",
    "CommitResult",
    "ControlActionResult",
    "ControlProjection",
    "FilesystemCheckpointPort",
    "GraphExecutorPort",
    "GraphWorkloadAdapter",
    "GraphWorkloadOutcome",
    "GraphWorkloadState",
    "JobCapabilities",
    "JobEvent",
    "JobEventType",
    "JobSnapshot",
    "JobSpec",
    "JobState",
    "LegacyCheckpointError",
    "OwnerRef",
    "RuntimeTaskBridge",
    "RuntimeTaskProjection",
    "SessionJobGate",
    "TaskWaitTimeout",
    "ShutdownPolicy",
    "ShutdownResult",
    "StopPolicy",
    "StopResult",
    "Subscription",
    "TaskAccessError",
    "TaskBackend",
    "TaskCancelled",
    "TaskEventFilter",
    "TaskProjectionPort",
    "TaskRuntime",
    "TerminalOutcome",
    "ThreadBackend",
    "TransitionError",
    "job_snapshot_to_public_dict",
    "job_snapshot_to_view",
    "job_spec_fingerprint",
    "view_age_seconds",
]
