"""Safe Project/Variant/Session persistence V2 kernel."""

from .filesystem import (
    FilesystemPort,
    OsPersistenceFilesystem,
    PersistenceFilesystemPort,
    RepositoryPaths,
)
from .ids import (
    EntityKind,
    OpaqueId,
    ProjectId,
    ProjectRef,
    SessionId,
    SessionRef,
    VariantId,
    VariantRef,
)
from .models import (
    SCHEMA_VERSION,
    AtomicWriteError,
    BackupVerificationError,
    FutureSchemaResult,
    LoadedRecord,
    MigrationReport,
    PathBoundaryError,
    ProjectDto,
    QuarantineRef,
    QuarantineResult,
    ReadOnlyWriteRefused,
    SchemaEnvelope,
    SchemaValidationError,
    SessionDto,
    VariantDto,
)
from .repository import ProjectRepository, SessionRepository, VariantRepository
from .schema import schema_for
from .variant import (
    FingerprintConflict,
    FingerprintMigrationPlan,
    MaterializationResult,
    SourceBaseline,
    SourceFingerprint,
    VariantAggregate,
    VariantChangeSet,
    VariantEntryState,
    VariantMaterializer,
    VariantSnapshot,
    collect_variant_snapshot,
)

__all__ = [
    "AtomicWriteError",
    "BackupVerificationError",
    "EntityKind",
    "FilesystemPort",
    "FingerprintConflict",
    "FingerprintMigrationPlan",
    "FutureSchemaResult",
    "LoadedRecord",
    "MigrationReport",
    "MaterializationResult",
    "OpaqueId",
    "OsPersistenceFilesystem",
    "PathBoundaryError",
    "PersistenceFilesystemPort",
    "ProjectDto",
    "ProjectId",
    "ProjectRef",
    "ProjectRepository",
    "QuarantineRef",
    "QuarantineResult",
    "ReadOnlyWriteRefused",
    "RepositoryPaths",
    "SCHEMA_VERSION",
    "SchemaEnvelope",
    "SchemaValidationError",
    "SessionDto",
    "SessionId",
    "SessionRef",
    "SessionRepository",
    "VariantDto",
    "SourceBaseline",
    "SourceFingerprint",
    "VariantAggregate",
    "VariantChangeSet",
    "VariantEntryState",
    "VariantId",
    "VariantRef",
    "VariantRepository",
    "VariantMaterializer",
    "VariantSnapshot",
    "collect_variant_snapshot",
    "schema_for",
]
