"""Headless Project/Variant lifecycle application surface."""

from .catalog import (
    VariantDescriptor,
    project_with_added_variant,
    project_without_variant,
    variant_catalog,
)
from .gui_facade import GuiProjectCommandFacade
from .legacy import LegacyProjectLifecycleAdapter
from .lifecycle import ProjectLifecycleService
from .models import (
    ActiveProject,
    DirtyDecision,
    ExportRevisionLease,
    LifecycleActivation,
    LifecycleEvent,
    LifecycleLease,
    LifecycleProjectUpdate,
    LifecycleSave,
    LifecycleSnapshot,
    PreparedTransition,
    TransitionTarget,
    project_with_active_variant,
)
from .ports import (
    CandidateLoaderPort,
    LifecycleLeasePort,
    LifecycleUnitOfWorkFactoryPort,
    LifecycleUnitOfWorkPort,
    NullLifecycleLeasePort,
)
from .provisioning import (
    PreparedProjectSource,
    PreparedSourceHydration,
    ProjectProvisioningCommit,
    ProjectProvisioningHydration,
    ProjectProvisioningHydrationResult,
    ProjectProvisioningIdentityPort,
    ProjectProvisioningLifecyclePort,
    ProjectProvisioningPreview,
    ProjectProvisioningRequest,
    ProjectProvisioningService,
    ProjectSourcePreparationPort,
    ProjectSourceRequest,
)
from .recent_catalog import ProjectCatalogEntry, ProjectCatalogQuery, ProjectCatalogSnapshot
from .remote_binding import (
    ParaTranzProjectBinding,
    ParaTranzTargetResolver,
    ParaTranzTargetSource,
    ParaTranzTargetStatus,
    ProjectRemoteBindingService,
    ResolvedParaTranzTarget,
    normalize_paratranz_endpoint,
    project_paratranz_binding,
    project_with_paratranz_binding,
)
from .source_commands import ProjectSourceMutationService, SourceMutationResult
from .variant_commands import EntryStatePatch

__all__ = [
    "ActiveProject",
    "CandidateLoaderPort",
    "DirtyDecision",
    "ExportRevisionLease",
    "EntryStatePatch",
    "LegacyProjectLifecycleAdapter",
    "LifecycleActivation",
    "LifecycleEvent",
    "LifecycleLease",
    "LifecycleProjectUpdate",
    "LifecycleLeasePort",
    "LifecycleSave",
    "LifecycleSnapshot",
    "LifecycleUnitOfWorkFactoryPort",
    "LifecycleUnitOfWorkPort",
    "NullLifecycleLeasePort",
    "PreparedTransition",
    "PreparedProjectSource",
    "PreparedSourceHydration",
    "ProjectProvisioningCommit",
    "ProjectProvisioningIdentityPort",
    "ProjectProvisioningLifecyclePort",
    "ProjectProvisioningHydration",
    "ProjectProvisioningHydrationResult",
    "ProjectProvisioningPreview",
    "ProjectProvisioningRequest",
    "ProjectProvisioningService",
    "ProjectCatalogEntry",
    "ProjectCatalogQuery",
    "ProjectCatalogSnapshot",
    "ProjectSourcePreparationPort",
    "ProjectSourceRequest",
    "ProjectSourceMutationService",
    "ProjectLifecycleService",
    "ProjectRemoteBindingService",
    "GuiProjectCommandFacade",
    "TransitionTarget",
    "VariantDescriptor",
    "project_with_added_variant",
    "project_with_active_variant",
    "project_without_variant",
    "variant_catalog",
    "ParaTranzProjectBinding",
    "ParaTranzTargetResolver",
    "ParaTranzTargetSource",
    "ParaTranzTargetStatus",
    "ResolvedParaTranzTarget",
    "SourceMutationResult",
    "normalize_paratranz_endpoint",
    "project_paratranz_binding",
    "project_with_paratranz_binding",
]
